<?php
/*Implementation of hook_block_info()*/
function widget_block_info() {
	//FOOTER
	$blocks['widget_twitter'] = array(
        'info' => t('[Elos] Latest Twitter'),
    );
	$blocks['widget_flickr'] = array(
        'info' => t('[Elos] Flickr Widget'),
    );
	$blocks['widget_latest_project_one'] = array(
      'info' => t('[Elos] Latest Projects 1'),
  	);
    return $blocks;
}

/*Implementation of hook_block_configure()*/
function widget_block_configure($delta = '') {
    $form = array();
    switch ($delta) {
		//FOOTER
		case 'widget_twitter':
            $form['widget_twitter_username'] = array(
                '#type' => 'textfield',
                '#title' => t('Your twitter username'),
                '#default_value' => variable_get('widget_twitter_username', 'envato'),
                '#description' => t('Eg: envato')
            );

            $form['widget_twitter_tweets_count'] = array(
                '#type' => 'select',
                '#title' => t('Number of recent tweets items to display'),
                '#default_value' => variable_get('widget_twitter_tweets_count', 2),
                '#options' => drupal_map_assoc(array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 25, 30)),
            );
            break;
		case 'widget_flickr':
            $form['widget_flickr_id'] = array(
                '#type' => 'textfield',
                '#title' => t('Your flickr ID'),
                '#default_value' => variable_get('widget_flickr_id', '52617155@N08'),
                '#description' => t('Eg: 52617155@N08')
            );
            $form['widget_flickr_photo_count'] = array(
                '#type' => 'select',
                '#title' => t('Number of recent photos items to display'),
                '#default_value' => variable_get('widget_flickr_photo_count', 6),
                '#options' => drupal_map_assoc(array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 25, 30)),
            );
            break;
		case 'widget_latest_project_one':
			$form['recent_works_block_count'] = array(
				'#type' => 'select',
				'#title' => t('Number of items to display'),
				'#default_value' => variable_get('recent_works_block_count', 8),
				'#options' => drupal_map_assoc(array(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 30, 40, 50, 60, 70, 80, 90, 100)),
			);
			break;
    }

    return $form;
}

/*Implementation of hook_block_save()*/

function widget_block_save($delta = '', $edit = array()) {
    switch ($delta) {
		//FOOTER
		case 'widget_twitter':
            variable_set('widget_twitter_username', $edit['widget_twitter_username']);
            variable_set('widget_twitter_tweets_count', $edit['widget_twitter_tweets_count']);
            break;
		case 'widget_flickr':
            variable_set('widget_flickr_id', $edit['widget_flickr_id']);
            variable_set('widget_flickr_photo_count', $edit['widget_flickr_photo_count']);
            break;
		case 'widget_latest_project_one':
			variable_set('recent_works_block_count', $edit['recent_works_block_count']);
			break;
    }
}

/*Implementation of hook_block_view()*/

function widget_block_view($delta = '') {
    // This example is adapted from node.module.
    $block = array();

    switch ($delta) {
		//FOOTER
		case 'widget_twitter':
            $block['title'] = widget_block_get_title($delta);
            $block['content'] = array(
                '#theme' => 'widget_twitter',
                '#settings' => array(
                    'widget_twitter_username' => variable_get('widget_twitter_username', 'envato'),
                    'widget_twitter_tweets_count' => variable_get('widget_twitter_tweets_count', 2),
                ),
            );
            break;
		case 'widget_flickr':
            $block['title'] = widget_block_get_title($delta);
			$block['content'] = array(
                '#theme' => 'widget_flickr',
                '#settings' => array(
                    'widget_flickr_id' => variable_get('widget_flickr_id', '52617155@N08'),
                    'widget_flickr_photo_count' => variable_get('widget_flickr_photo_count', 6),
                ),
            );
            break;
		case 'widget_latest_project_one':
			$node_limit = variable_get('recent_works_block_count', 8);
			$content_type = 'portfolio';
			$query = db_query('SELECT n.nid FROM {node} n WHERE n.type = :type AND n.status = 1 ORDER BY n.created DESC LIMIT 0, ' . $node_limit, array(':type' => $content_type));
			$nids = $query->fetchCol();
			$nodes = node_load_multiple($nids);
			$block['title'] = '';
			
			if (!empty($nodes)) {
				$block['content'] = array(
					'#theme' => 'widget_latest_project_one',
					'#nodes' => $nodes,
					'#title' => widget_block_get_title($delta),
					
				);
			}
			
			break;
		
    }
    return $block;
}

/*Implementation of hook_theme()*/
function widget_theme($existing, $type, $theme, $path) {
    return array(
		
		//FOOTER
		'widget_twitter' => array(
            'variables' => array('settings' => array('widget_twitter_username' => NULL, 'widget_twitter_tweets_count' => NULL)),
            'template' => 'widget_twitter'
        ),
		'widget_flickr' => array(
            'variables' => array('settings' => array('widget_flickr_id' => NULL, 'widget_flickr_photo_count' => NULL)),
            'template' => 'widget_flickr'
        ),
		'widget_latest_project_one' => array(
			'variables' => array('nodes' => NULL, 'title' => NULL),
			'template' => 'widget_latest_project_one',
		),
    );
}

function widget_block_get_title($delta) {
  $block = db_query('SELECT title FROM {block} WHERE delta = :delta', array(':delta' => $delta))->fetchObject();
  return $block->title ? $block->title : '';
}


function widget_trim_text($alter, $value) {
	if (drupal_strlen($value) > $alter['max_length']) {
		$value = drupal_substr($value, 0, $alter['max_length']);
		// TODO: replace this with cleanstring of ctools
		if (!empty($alter['word_boundary'])) {
			$regex = "(.*)\b.+";
			if (function_exists('mb_ereg')) {
				mb_regex_encoding('UTF-8');
				$found = mb_ereg($regex, $value, $matches);
			} else {
				$found = preg_match("/$regex/us", $value, $matches);
			}
			if ($found) {
				$value = $matches[1];
			}
		}
		// Remove scraps of HTML entities from the end of a strings
		$value = rtrim(preg_replace('/(?:<(?!.+>)|&(?!.+;)).*$/us', '', $value));
		
		if (!empty($alter['ellipsis'])) {
			$value .= t('...');
		}
	}
	if (!empty($alter['html'])) {
		$value = _filter_htmlcorrector($value);
	}

	return $value;
}


//delete attributes width, height.
function widget_preprocess_image(&$variables) {
  foreach (array('width', 'height') as $key) {
    unset($variables[$key]);
  }
}


function widget_format_terms($field_category, $node, $limit = NULL) {
  
    $category_arr = array();
    $category = '';
    
    if (!empty($node->{$field_category}[LANGUAGE_NONE])) {
        foreach ($node->{$field_category}[LANGUAGE_NONE] as $item) {
            $term = taxonomy_term_load($item['tid']);
            if ($term) {
                $category_arr[] = $term->name;
            }

            if ($limit) {
                if (count($category_arr) == $limit) {
                    $category = implode(', ', $category_arr);
                    return $category;
                }
            }
        }
    }
    $category = implode(', ', $category_arr);

    return $category;
}